services:
  - type: web
    name: archefc-backend
    env: node
    buildCommand: cd backend && npm install && npm run build && npx prisma db push && npx prisma db seed
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: archefc-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000

databases:
  - name: archefc-db
    databaseName: archefc
    user: archefc
    plan: free 